# global.R
library(shiny)
library(plotly)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reactable)
library(shinythemes)
library(shinythemes)
library(shinydashboard)
library(shinyWidgets)
library(readr)
library(countrycode)
source("R/source_deploy.R")
